local _, ns = ...
local L = LibStub("AceLocale-3.0"):GetLocale("MidnightRoutine", true)

local T, S, WQ, WD, DMF, TR, Ref = ns.T, ns.S, ns.WQ, ns.WD, ns.DMF, ns.TR, ns.Ref
local DRAGONFLIGHT_CATCHUP_ITEM_ID = ns.DRAGONFLIGHT_CATCHUP_ITEM_ID

local DRAGONFLIGHT_EXPANSION = {
        key = "dragonflight",
        label = L["ProfKnowledge_LegacySection_Dragonflight"] or "Dragonflight",
        shortLabel = L["ProfKnowledge_LegacySection_Dragonflight"] or "Dragonflight",
        sharedCatchupItemID = DRAGONFLIGHT_CATCHUP_ITEM_ID,
        professions = {
            { key = "alchemy", label = L["Alchemy"], skillLine = 2823, weekly = {
                TR{ itemID = 194697, questID = 74108, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 75363, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75371, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77932, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77933, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66937, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66938, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66940, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72427, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70530, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70531, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70532, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70533, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70289, kp = 3, zone = 2022, x = 25.1, y = 73.3, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70274, kp = 3, zone = 2022, x = 55.0, y = 81.0, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70305, kp = 3, zone = 2023, x = 79.2, y = 83.8, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70208, kp = 3, zone = 2024, x = 16.4, y = 38.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70309, kp = 3, zone = 2024, x = 67.0, y = 13.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70278, kp = 3, zone = 2025, x = 55.2, y = 30.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70301, kp = 3, zone = 2025, x = 59.5, y = 38.4, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75649, kp = 3, zone = 2133, x = 62.10, y = 41.12, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75646, kp = 3, zone = 2133, x = 52.68, y = 18.30, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75651, kp = 3, zone = 2133, x = 40.48, y = 59.18, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "blacksmithing", label = L["Blacksmithing"], skillLine = 2822, weekly = {
                TR{ itemID = 198454, questID = 74109, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70589, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75148, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75569, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77935, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77936, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66517, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66897, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66941, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72398, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70211, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70233, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70234, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70235, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70232, kp = 3, zone = 2022, x = 56.4, y = 19.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70246, kp = 3, zone = 2022, x = 22.0, y = 87.0, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70312, kp = 3, zone = 2022, x = 65.5, y = 25.7, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70296, kp = 3, zone = 2022, x = 35.5, y = 64.3, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70310, kp = 3, zone = 2022, x = 34.5, y = 67.1, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70313, kp = 3, zone = 2023, x = 81.1, y = 37.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70353, kp = 3, zone = 2023, x = 50.9, y = 66.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70314, kp = 3, zone = 2024, x = 53.1, y = 65.3, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70311, kp = 3, zone = 2025, x = 52.2, y = 80.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76079, kp = 3, zone = 2133, x = 48.30, y = 21.95, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76078, kp = 3, zone = 2133, x = 57.15, y = 54.64, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76080, kp = 3, zone = 2133, x = 27.53, y = 42.87, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "enchanting", label = L["Enchanting"], skillLine = 2825, weekly = {
                TR{ itemID = 194702, questID = 74110, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 75150, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75865, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77910, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77937, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66884, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66900, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66935, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72423, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72155, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72172, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72173, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72175, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70320, kp = 3, zone = 2022, x = 57.5, y = 83.6, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70283, kp = 3, zone = 2022, x = 68.0, y = 26.8, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70272, kp = 3, zone = 2022, x = 57.5, y = 58.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70291, kp = 3, zone = 2023, x = 61.4, y = 67.6, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70336, kp = 3, zone = 2024, x = 38.5, y = 59.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70290, kp = 3, zone = 2024, x = 45.1, y = 61.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70298, kp = 3, zone = 2024, x = 21.0, y = 45.0, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70342, kp = 3, zone = 2025, x = 59.9, y = 70.4, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75508, kp = 3, zone = 2133, x = 48.00, y = 17.00, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75510, kp = 3, zone = 2133, x = 36.66, y = 69.33, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75509, kp = 3, zone = 2133, x = 62.39, y = 53.80, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "engineering", label = L["Engineering"], skillLine = 2827, weekly = {
                TR{ itemID = 198510, questID = 74111, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70591, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75575, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75608, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77891, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77938, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66890, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66891, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66942, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72396, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70539, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70540, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70545, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70557, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70270, kp = 3, zone = 2022, x = 56.0, y = 44.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70275, kp = 3, zone = 2022, x = 49.09, y = 77.54, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75186, kp = 3, zone = 2133, x = 37.82, y = 58.83, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75184, kp = 3, zone = 2133, x = 50.51, y = 47.93, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75431, kp = 3, zone = 2133, x = 49.44, y = 79.01, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75430, kp = 3, zone = 2133, x = 57.65, y = 73.94, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75183, kp = 3, zone = 2133, x = 48.17, y = 27.93, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75188, kp = 3, zone = 2133, x = 49.87, y = 59.25, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75180, kp = 3, zone = 2133, x = 48.48, y = 48.64, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75433, kp = 3, zone = 2133, x = 48.10, y = 16.59, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "herbalism", label = L["Herbalism"], skillLine = 2832, weekly = {
                TR{ itemID = 194704, questID = 74107, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 71857, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71858, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71859, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71860, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71861, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71864, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 70613, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70614, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70615, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70616, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "inscription", label = L["Inscription"], skillLine = 2828, weekly = {
                TR{ itemID = 194699, questID = 74105, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70592, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75149, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75573, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77889, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77914, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66943, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66944, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66945, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72438, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70558, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70559, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70560, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70561, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70306, kp = 3, zone = 2022, x = 67.87, y = 57.96, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70307, kp = 3, zone = 2023, x = 85.7, y = 25.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70297, kp = 3, zone = 2024, x = 46.2, y = 23.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70293, kp = 3, zone = 2024, x = 43.7, y = 30.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70281, kp = 3, zone = 2112, x = 13.2, y = 63.68, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70264, kp = 3, zone = 2025, x = 56.3, y = 41.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70248, kp = 3, zone = 2025, x = 47.24, y = 40.1, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70287, kp = 3, zone = 2025, x = 56.1, y = 40.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76120, kp = 3, zone = 2133, x = 53.01, y = 74.27, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76121, kp = 3, zone = 2133, x = 54.57, y = 20.21, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76117, kp = 3, zone = 2133, x = 36.73, y = 46.32, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "jewelcrafting", label = L["Jewelcrafting"], skillLine = 2829, weekly = {
                TR{ itemID = 194703, questID = 74112, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70593, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75362, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75602, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77892, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77912, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66516, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66949, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66950, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72428, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70562, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70563, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70564, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70565, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70292, kp = 3, zone = 2022, x = 50.4, y = 45.1, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70273, kp = 3, zone = 2022, x = 33.9, y = 63.7, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70282, kp = 3, zone = 2023, x = 25.2, y = 35.4, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70263, kp = 3, zone = 2023, x = 61.8, y = 13.0, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70277, kp = 3, zone = 2024, x = 45.0, y = 61.3, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70271, kp = 3, zone = 2024, x = 44.6, y = 61.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70285, kp = 3, zone = 2025, x = 59.8, y = 65.2, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70261, kp = 3, zone = 2025, x = 56.91, y = 43.72, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75654, kp = 3, zone = 2133, x = 54.41, y = 32.47, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75653, kp = 3, zone = 2133, x = 34.47, y = 45.43, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75652, kp = 3, zone = 2133, x = 40.37, y = 80.66, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "leatherworking", label = L["Leatherworking"], skillLine = 2830, weekly = {
                TR{ itemID = 194700, questID = 74113, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70594, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75354, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75368, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77945, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77946, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66363, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66364, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66951, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72407, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70567, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70568, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70569, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70571, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70308, kp = 3, zone = 2022, x = 39.0, y = 86.0, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70280, kp = 3, zone = 2022, x = 64.3, y = 25.4, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70300, kp = 3, zone = 2023, x = 86.4, y = 53.7, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70269, kp = 3, zone = 2024, x = 12.5, y = 49.4, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70266, kp = 3, zone = 2024, x = 16.7, y = 38.8, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70286, kp = 3, zone = 2024, x = 57.5, y = 41.3, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70294, kp = 3, zone = 2025, x = 56.8, y = 30.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75495, kp = 3, zone = 2133, x = 41.16, y = 48.81, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75496, kp = 3, zone = 2133, x = 45.25, y = 21.12, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75502, kp = 3, zone = 2133, x = 49.56, y = 54.80, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "mining", label = L["Mining"], skillLine = 2833, weekly = {
                TR{ itemID = 194708, questID = 74106, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 72160, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72161, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72162, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72163, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72164, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72165, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 70617, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70618, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72156, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72157, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "skinning", label = L["Skinning"], skillLine = 2834, weekly = {
                TR{ itemID = 201023, questID = 74114, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70381, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70383, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70384, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70385, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70386, kp = 1, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70389, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 70619, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70620, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72158, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72159, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
            { key = "tailoring", label = L["Tailoring"], skillLine = 2831, weekly = {
                TR{ itemID = 194698, questID = 74115, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70595, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75407, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75600, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77947, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77949, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66899, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66952, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66953, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72410, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70572, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70582, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70586, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70587, kp = 3, note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70302, kp = 3, zone = 2022, x = 74.7, y = 37.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70304, kp = 3, zone = 2022, x = 24.9, y = 69.7, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70295, kp = 3, zone = 2023, x = 35.34, y = 40.12, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70303, kp = 3, zone = 2023, x = 66.1, y = 52.9, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70284, kp = 3, zone = 2024, x = 16.2, y = 38.8, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70267, kp = 3, zone = 2024, x = 40.7, y = 54.5, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70288, kp = 3, zone = 2025, x = 60.4, y = 79.7, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70372, kp = 3, zone = 2025, x = 58.6, y = 45.8, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76102, kp = 3, zone = 2133, x = 47.21, y = 48.55, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76116, kp = 3, zone = 2133, x = 44.52, y = 15.65, note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76110, kp = 3, zone = 2133, x = 59.11, y = 73.14, note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_100_artisan_s_mettle_preferred_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_150_artisan_s_mettle_valued_rep"] },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, note = L["ProfKnowledge_Note_rabul_valdrakken_200_artisan_s_mettle_esteemed_rep"] },
            } },
        },
}

ns.RegisterProfessionExpansion(DRAGONFLIGHT_EXPANSION)
for _, profession in ipairs(DRAGONFLIGHT_EXPANSION.professions or {}) do
    ns.RegisterProfessionMainMenuModule(profession, DRAGONFLIGHT_EXPANSION)
end
